# Generated by Django 5.1.5 on 2026-05-20 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
