# Generated by Django 5.1.5 on 2026-05-19 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blueprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('exam', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=50)),
                ('total_marks', models.IntegerField(default=0)),
                ('neg_marking', models.CharField(default='', max_length=100)),
                ('sections', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blueprints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pd_blueprints',
                'ordering': ['-created_at'],
            },
        ),
    ]
